# Generated by Django 5.1.3 on 2025-01-22 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('case', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AWSAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=50, unique=True)),
                ('aws_access_key', models.CharField(max_length=100)),
                ('aws_secret_key', models.CharField(max_length=100)),
                ('aws_region', models.CharField(default='us-east-1', max_length=50)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('validated', models.BooleanField(default=False)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_aws_accounts', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aws_accounts', to='case.case')),
            ],
        ),
        migrations.CreateModel(
            name='AWSLogSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('log_name', models.CharField(max_length=255)),
                ('log_details', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('aws_region', models.CharField(blank=True, max_length=50, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_sources', to='aws.awsaccount')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aws_log_sources', to='case.case')),
            ],
        ),
        migrations.CreateModel(
            name='AWSResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_id', models.CharField(max_length=200)),
                ('resource_type', models.CharField(max_length=100)),
                ('resource_name', models.CharField(blank=True, max_length=200, null=True)),
                ('resource_details', models.JSONField(blank=True, null=True)),
                ('aws_region', models.CharField(blank=True, max_length=50, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='aws.awsaccount')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aws_resources', to='case.case')),
            ],
        ),
        migrations.CreateModel(
            name='AWSCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=300)),
                ('user_arn', models.CharField(max_length=300)),
                ('user_creation_time', models.DateTimeField(blank=True, null=True)),
                ('password_enabled', models.BooleanField(default=False)),
                ('password_last_used', models.DateTimeField(blank=True, null=True)),
                ('password_last_changed', models.DateTimeField(blank=True, null=True)),
                ('password_next_rotation_date', models.DateTimeField(blank=True, null=True)),
                ('mfa_active', models.BooleanField(default=False)),
                ('access_key_1_active', models.BooleanField(default=False)),
                ('access_key_1_last_rotated', models.DateTimeField(blank=True, null=True)),
                ('access_key_1_last_used_date', models.DateTimeField(blank=True, null=True)),
                ('access_key_1_last_used_region', models.CharField(blank=True, max_length=300, null=True)),
                ('access_key_1_last_used_service', models.CharField(blank=True, max_length=300, null=True)),
                ('access_key_2_active', models.BooleanField(default=False)),
                ('access_key_2_last_rotated', models.DateTimeField(blank=True, null=True)),
                ('access_key_2_last_used_date', models.DateTimeField(blank=True, null=True)),
                ('access_key_2_last_used_region', models.CharField(blank=True, max_length=300, null=True)),
                ('access_key_2_last_used_service', models.CharField(blank=True, max_length=300, null=True)),
                ('cert_1_active', models.BooleanField(default=False)),
                ('cert_1_last_rotated', models.DateTimeField(blank=True, null=True)),
                ('cert_2_active', models.BooleanField(default=False)),
                ('cert_2_last_rotated', models.DateTimeField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='aws.awsaccount')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aws_credentials', to='case.case')),
            ],
            options={
                'unique_together': {('account', 'user')},
            },
        ),
    ]
