# Generated by Django 5.1.3 on 2024-12-22 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='awsresource',
            name='aws_region',
            field=models.CharField(default='us-east-1', max_length=50),
        ),
    ]
