# Generated by Django 5.1.3 on 2025-01-24 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0001_initial'),
        ('data', '0003_normalizedlog_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='awscredential',
            name='tags',
            field=models.ManyToManyField(related_name='aws_credential', to='data.tag'),
        ),
        migrations.AddField(
            model_name='awslogsource',
            name='tags',
            field=models.ManyToManyField(related_name='aws_log_source', to='data.tag'),
        ),
        migrations.AddField(
            model_name='awsresource',
            name='tags',
            field=models.ManyToManyField(related_name='aws_resource', to='data.tag'),
        ),
    ]
