# Generated by Django 5.1.3 on 2025-01-08 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awsresource',
            name='aws_region',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
