# Generated by Django 5.1.3 on 2024-12-23 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0002_awsresource_aws_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='awsaccount',
            name='validated',
            field=models.BooleanField(default=False),
        ),
    ]
