# Generated by Django 5.1.3 on 2025-01-08 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0002_alter_awsresource_aws_region'),
        ('case', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AWSLogSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('log_name', models.CharField(max_length=255)),
                ('log_details', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('aws_region', models.CharField(blank=True, max_length=50, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_sources', to='aws.awsaccount')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aws_log_sources', to='case.case')),
            ],
        ),
    ]
