# Generated by Django 5.1.3 on 2024-12-22 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='status',
            field=models.CharField(blank=True, choices=[('investigating', 'Investigating'), ('closed', 'Closed')], max_length=100, null=True),
        ),
    ]
