# Generated by Django 5.1.3 on 2025-01-20 04:31

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aws', '0001_initial'),
        ('case', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalizedLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_id', models.CharField(blank=True, max_length=255, null=True)),
                ('log_source', models.CharField(choices=[('aws', 'Amazon Web Services'), ('gcp', 'Google Cloud Platform'), ('azure', 'Microsoft Azure')], db_index=True, max_length=50)),
                ('log_type', models.CharField(db_index=True, max_length=100)),
                ('event_name', models.CharField(db_index=True, max_length=255)),
                ('event_time', models.DateTimeField(db_index=True)),
                ('user_identity', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('resources', models.TextField(blank=True, null=True)),
                ('raw_data', models.TextField()),
                ('extra_data', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('aws_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_logs', to='aws.awsaccount')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_logs', to='case.case')),
            ],
            options={
                'indexes': [django.contrib.postgres.indexes.BTreeIndex(fields=['log_source'], name='data_normal_log_sou_bee0df_btree'), django.contrib.postgres.indexes.BTreeIndex(fields=['log_type'], name='data_normal_log_typ_a9e795_btree'), django.contrib.postgres.indexes.BTreeIndex(fields=['event_name'], name='data_normal_event_n_8b8bea_btree'), django.contrib.postgres.indexes.BTreeIndex(fields=['event_time'], name='data_normal_event_t_c05244_btree'), django.contrib.postgres.indexes.BTreeIndex(fields=['ip_address'], name='data_normal_ip_addr_3df897_btree')],
            },
        ),
    ]
