# Generated by Django 5.1.3 on 2025-01-08 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0002_alter_awsresource_aws_region'),
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='normalizedlog',
            name='aws_resource',
        ),
        migrations.AddField(
            model_name='normalizedlog',
            name='aws_resources',
            field=models.ManyToManyField(related_name='normalized_logs', to='aws.awsresource'),
        ),
        migrations.AddField(
            model_name='normalizedlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
