# Generated by Django 5.1.3 on 2025-01-08 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_remove_normalizedlog_aws_resource_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='normalizedlog',
            name='log_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
