# Generated by Django 5.1.3 on 2025-01-24 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0001_initial'),
        ('data', '0003_normalizedlog_tags'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='normalizedlog',
            unique_together={('case', 'event_id')},
        ),
    ]
